[package]
name = "brc-impl"
version = "0.1.0"
edition = "2024"

[[bench]]
name = "full_run"
harness = false

[dependencies]
fnv = "1.0.3"

[dev-dependencies]
criterion = { version = "0.8", features = ["html_reports"] }
